-- Task 1
-- JOINING 2 TABLES ON MATCHES ONLY, THEREFORE PRODUCERS WITHOUT MOVIES WILL NOT BE PRESENT
-- AFTER THAT WE GROUP BY ALL THE NECESSARY COLUMNS TO FIND COUNT PER YEAR FOR A PRODUCER
SELECT ME.NAME, M.YEAR, COUNT(*) AS CNT FROM MOVIEEXEC ME
JOIN MOVIE M ON ME.CERT = M.PRODUCERC
GROUP BY ME.CERT, ME.NAME, M.YEAR;


-- Task 2
-- GET ALL MOVIESTARS, ORDER THEM BY BIRTHDATE IN DESCENDING ORDER (2000, 1990, 1980...), GET THE FIRST RECORD, WHICH IS THE YOUNGEST MOVIESTAR
SELECT * FROM MOVIESTAR
ORDER BY BIRTHDATE DESC
LIMIT 1;
